# This action will build and upload a codemodder base image that will be used in the codemod integration tests.
name: Build and push codemodder base image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push codemodder base image
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Generate distribution
        run: make generate-tar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: core-codemods/src/test/java/io/codemodder/codemods/integration/baseimage/Dockerfile
          push: true
          # replace personal account
          tags: arturoiwa/codemodder-base:latest

