on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v11
        with:
          repositories: >
            [
              {
                "id": "central",
                "name": "central",
                "url": "https://pixee.jfrog.io/artifactory/mailman-libs-snapshot",
                "releases": {
                  "enabled": "false",
                  "updatePolicy": "always",
                  "checksumPolicy": "fail"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always",
                  "checksumPolicy": "fail"
                }
              }
            ]
          servers: |
            [
              {
                "id": "central",
                "username": "${env.ARTIFACTORY_USERNAME_REF}",
                "password": "${env.ARTIFACTORY_TOKEN_REF}"
              }
            ]
      - name: Build with Maven
        run: mvn install deploy -DaltDeploymentRepository=central::default::https://pixee.jfrog.io/artifactory/mailman-libs-snapshot

