name: Create Release on Semantic Version Tag

on:
  push:
    branches:
      - master

env:
  M2_HOME: /opt/hostedtoolcache/maven/3.8.2

jobs:
  pre-release:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - id: setup-java
        name: "Build, test and deploy"
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: "Setting up Artifactory authentication"
        uses: s4u/maven-settings-action@v2
        with:
          servers: |
            [
              {"id": "pixee-libs-release", "username": "${{ secrets.ARTIFACTORY_USER }}", "password": "${{ secrets.ARTIFACTORY_TOKEN }}"},
              {"id": "pixee-libs-snapshot", "username": "${{ secrets.ARTIFACTORY_USER }}", "password": "${{ secrets.ARTIFACTORY_TOKEN }}"}
            ]
          githubServer: false

      - name: Build with Maven
        run: |
          mvn -N -B install 
          env
          echo `which java`

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          JAVA_HOME: "${{ steps.setup-java.outputs.path }}"
